spring.application.name=llama.cppAi


server.port=9090

spring.ai.openai.base-url=http://localhost:8080/v1
spring.ai.openai.api-key=dummy
spring.ai.openai.chat.options.model=local-model

# ?????????? ???? ?? ?????
spring.ai.model.embedding=none

# ????????? ???????????????? ????????????.
# ????? Spring ??????? ???? ??? OpenAiAudioTranscriptionModel,
# ???????????? ?? spring.ai.openai.base-url (???? 8080 ? ??? ???, ? ?? Whisper),
# ? ????????? ??? ???? ?????? ???? ? @Autowired ?? ?????? ???????.
spring.ai.model.audio.transcription=none

# ???????? ???????????. ?? ????????? ????? 1 ?? ? ????? ?? ??????.
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

spring.ai.openai.chat.options.max-tokens=120
spring.ai.openai.chat.options.temperature=0.3

piper.exe=C:/ai/piper2/piper.exe
piper.model=C:/ai/piper2/tr_TR-dfki-medium.onnx